[general]
repository = "https://github.com/Kesomannen/CompetitiveCompany"

[package]
name = "CompetitiveCompany2"
namespace = "Kesomannen"
description = "Introduces a new PvP scrap-collecting gamemode to the game"
websiteUrl = "https://github.com/Kesomannen/CompetitiveCompany"
dependencies = [
    "BepInEx-BepInExPack-5.4.2100",
    "Kesomannen-ComponentBundler-1.0.1",
    "Evaisa-FixPluginTypesSerialization-1.1.1",
    "LethalAPI-LethalAPI_Terminal-1.0.1",
    "Evaisa-LethalLib-0.16.1",
    "Rune580-LethalCompany_InputUtils-0.7.7",
    "Evaisa-HookGenPatcher-0.0.5"
]

[build]
icon = "icon.png"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE.md"
target = "LICENSE.md"

[[build.copy]]
source = "CompetitiveCompany\\bin\\Release\\netstandard2.1\\CompetitiveCompany.dll"
target = "CompetitiveCompany.dll"

[[build.copy]]
source = "CompetitiveCompany\\lib\\FlowTween.dll"
target = "FlowTween.dll"

[publish]
communities = ["lethal-company"]
lethal-company.categories = ["serverside", "clientside", "mods"]
